---
# tasks file for myapache
          - name: Install httpd
            package:
                    name: "{{ item }}"
                    state: present
            loop: "{{ pkgs }}"

          - name: Copy the webpage
            template:
                    src: "index.html.j2"
                    dest: "/var/www/html/index.html"

          - name: Start webserver service
            service:
                    name: "{{ item }}"
                    state: started
                    enabled: yes
            loop: "{{ pkgs }}"

          - name: Firewall rule create
            firewalld:
                    service: "{{ item }}"
                    state: enabled
                    permanent: yes
                    immediate: yes
            loop: "{{ rule }}"

